swagger: '2.0'
info:
  title: API de Previsão
  description: Documentação da API de Previsão
paths:
  /predict:
    post:
      summary: Endpoint para previsão
      requestBody:
        description: JSON de entrada para previsão
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Resposta bem-sucedida
          content:
            application/json:
              schema:
                type: object
                properties:
                  predicao:
                    type: array
                    items:
                      type: number
