# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python


name: api-deploy

on:
  push:
    branches: [ "deploy_deploy" ]
    paths:
      - 'src/api/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "alessitomas"
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./src/api
        file: ./src/api/Dockerfile
        push: true
        tags: alessitomas/api-deploy:${{ github.sha }}
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_TEST }}
        username: "ec2-user"
        key: ${{ secrets.KEY_TEST }}
        port: 22
        script: |
              if [ $(docker ps -aq -f name=api-deploy) ]; then
                  docker stop api-deploy
                  docker rm --force api-deploy
              fi
              docker run -e API_KEY_ANA=${{ secrets.API_KEY_ANA }} -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} -d -p 8082:5000 --name api-deploy alessitomas/api-deploy:${{ github.sha }}
